### ISSUE TITLE
`material-ui-icons` is too big

### ISSUE THREAD

**Issue by gimdongwoo** [b-gran/object-editor-react#10]
Thank you.

Fisrt of all, `object-editor-react` is a great components!

But, `object-editor-react` need to tree shaking.

![2018-05-13 6 46 52](https://user-images.githubusercontent.com/7310854/39965952-2c50feb0-56de-11e8-9484-d895f3eb31fb.png)

**Comment by b-gran** [comment]
Thanks for opening an issue @gimdongwoo. 

I'll look into the bundle size. What tool did you use to generate this visualization?

**Comment by gimdongwoo** [comment]
Here :)
https://www.npmjs.com/package/webpack-bundle-analyzer

And, this warning is appeared on build.
```
npm WARN deprecated material-ui-icons@1.0.0-beta.36: Use @material-ui/icons instead
```

**Comment by gimdongwoo** [comment]
[before]
![kakaotalk_photo_2018-05-13-22-30-50](https://user-images.githubusercontent.com/7310854/39967813-5dd89474-56fd-11e8-8db1-51973e309044.png)

[after]
![2018-05-13 10 30 11](https://user-images.githubusercontent.com/7310854/39967815-681753a8-56fd-11e8-8d6c-8b9e966350d1.png)

I really appreciate your super fast response!

**Comment by b-gran** [comment]
Happy to hear this helped 😄 I've also got plans to improve the bundle even more in the future.

Going to close this for now but feel free to raise another issue if the bundle size is still giving you trouble.
