### ISSUE TITLE
can't resolve symbols  

### ISSUE THREAD

**Issue by maksmaers** [b-gran/object-editor-react#12]
Hi I have an issue, can't resolve symbols by 

import { **SchemaTypes** } from 'object-editor-react';
import { **ArrayEditor**, **ObjectEditor** } from 'object-editor-react';

**Comment by b-gran** [comment]
Hi @maksmaers 

Could you provide some more information about the problem you're having?

Specifically, could you include the following:
* the exact error message you're seeing, copy/pasted
* `node --version` and `npm --version`
* details about your build process (e.g. are you using `webpack`? some other bundler? `typescript`?)
* `object-editor-react` version you're using

Thanks :)

**Comment by b-gran** [comment]
Hi @maksmaers 

Were you able to resolve this?

**Comment by b-gran** [comment]
Hi @maksmaers 

I'm going to close this for now, but I'm happy to reopen it if we're able to reproduce it
