### ISSUE TITLE
rowsPerPage as props?

### ISSUE THREAD

**Issue by yorickreum** [b-gran/object-editor-react#36]
Hey there,

Thanks for your contribution to the open source world, this components look pretty cool.
Is it possible to pass rowsPerPage as props? Five rows is really not enough for our project...

Kind regards from Würzburg
Yorick

**Comment by b-gran** [comment]
Hi @yorickreum 

A new prop, `defaultRowsPerPage` is added in version 1.1.0

**Comment by yorickreum** [comment]
Thanks a lot!
