### ISSUE TITLE
Schemas can not contain a key named 'type'

### ISSUE THREAD

**Issue by ulabs-sgiroux** [b-gran/object-editor-react#5]
Test:
/src/test/index.js Line 28, change 'foo' to 'type'
Open demo page and edit 'test' field.

There is an exception on line 330 of Editor.js:
`(this.props.type.type && this.props.type.type.match(/array/) !== null) ||`
where this.props.type.type.match is not a function.

If you are attaching 'type' for schema checking/validation, perhaps it could be renamed to something a schema would not be likely to contain like ____________type____ :sunglasses:

**Comment by b-gran** [comment]
Good catch. How about `_type`? mongoose has this problem too and it's really annoying

**Comment by ulabs-sgiroux** [comment]
I think that is entirely reasonable. There is a separate issue with regards to how arrays are handled that I am trying to work my head around.
