### ISSUE TITLE
Incompatibility with bootstrap css 'row'

### ISSUE THREAD

**Issue by ulabs-sgiroux** [b-gran/object-editor-react#9]
At https://github.com/b-gran/object-editor-react/blob/abc7a9f288443db397ba7c74c05adb034daf60ca/src/Editor.js#L569
an elementrow's table -> tbody -> tr gets className 'row row--object'.

'row' is used in bootstrap and breaks table alignment.

I propose we either use less classnames or use more unique classnames. Additionally the out-of-box styles play very poorly with bootstrap.

**Comment by b-gran** [comment]
Unique classnames is a better choice, since compared to descendant and children selectors class selectors are _way_ faster.
Plus, you don't need to know the exact structure of the markup to use class selectors, you just need the name of the class you want to style.

**Comment by b-gran** [comment]
Renamed `.row` -> `.editor__row`
